# Generated by Django 5.0.7 on 2024-07-28 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='ParentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(max_length=200, verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('grade_level', models.CharField(max_length=20, verbose_name='Grade Level')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('day_type', models.CharField(choices=[('A', 'A Day'), ('B', 'B Day')], max_length=1, verbose_name='Day Type')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.instructor', verbose_name='Instructor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.subject', verbose_name='Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('grade', models.CharField(max_length=20, verbose_name='Grade')),
                ('parent_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.parentcontact', verbose_name='Parent Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], max_length=10, verbose_name='Status')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.classsession', verbose_name='Class Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.student', verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.instructor', verbose_name='Instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.student', verbose_name='Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.subject', verbose_name='Subject')),
            ],
        ),
    ]
