# Generated by Django 5.0.7 on 2024-08-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instructors',
            field=models.ManyToManyField(related_name='customusers', to='tracker.instructor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
